ASSUME CS:CODE,DS:DATA 
DATA SEGMENT 
LIST Db 53H,25H,19H,02H 
COUNT EQU 04H 
MIN DB ? 
MAX DB ? 
DATA ENDS 
CODE SEGMENT 
START:MOV AX,DATA 
 MOV DS,AX 
 XOR DX,DX 
 XOR CX,CX 
 MOV DL,COUNT-1 
 AGAIN0:MOV CL,DL 
 MOV SI,OFFSET LIST 
 AGAIN1:MOV AL,[SI] 
 CMP AL,[SI+1] 
 JL PR1 
 XCHG [SI+1],AL 
 XCHG [SI],AL 
 PR1:INC SI 
 LOOP AGAIN1 
 DEC DL 
 JNZ AGAIN0 
 MOV SI,OFFSET LIST 
 MOV AL,[SI] 
 MOV MIN,AL 
 MOV AL,[SI+COUNT-1] 
 MOV MAX,AL 
 MOV AH,4CH 
 INT 21H 
 CODE ENDS 
 END START 
